# Terraform Provider release workflow.
name: Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write
    id-token: write
    packages: write

jobs:
    prepare:
        strategy:
            matrix:
                GOOS: [linux, windows, darwin, freebsd]

        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            with:
                # Allow goreleaser to access older tag information.
                fetch-depth: 0
          - name: Setup Go
            uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
            with:
                go-version-file: "go.mod"
                cache: true
          - shell: bash
            run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          - name: OS Release Cache
            id: cache
            uses: actions/cache@v4
            with:
                path: dist/${{ matrix.GOOS }}
                key: ${{ matrix.GOOS }}-${{ env.sha_short }}
          - name: Import GPG key
            uses: crazy-max/ghaction-import-gpg@v6
            id: import_gpg
            with:
                gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                passphrase: ${{ secrets.PASSPHRASE }}
          - name: Prepare dist/${{ matrix.GOOS }}
            uses: goreleaser/goreleaser-action@v6
            if: steps.cache.outputs.cache-hit != 'true'
            with:
                distribution: goreleaser-pro
                version: latest
                args: release --clean --split --timeout 1h
            env:
                GGOOS: ${{ matrix.GOOS }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
                GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

    release:
        runs-on: ubuntu-latest
        needs: prepare
        steps:
          - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            with:
                fetch-depth: 0
          - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
            with:
                go-version-file: "go.mod"
                cache: true

            # copy the cashes from prepare
          - shell: bash
            run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          - uses: actions/cache@v4
            with:
                path: dist/linux
                key: linux-${{ env.sha_short }}
          - uses: actions/cache@v4
            with:
                path: dist/darwin
                key: darwin-${{ env.sha_short }}
          - uses: actions/cache@v4
            with:
                path: dist/windows
                key: windows-${{ env.sha_short }}
          - uses: actions/cache@v4
            with:
                path: dist/freebsd
                key: freebsd-${{ env.sha_short }}


                # release
          - name: Import GPG key
            uses: crazy-max/ghaction-import-gpg@v6
            id: import_gpg
            with:
                gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                passphrase: ${{ secrets.PASSPHRASE }}
          - uses: goreleaser/goreleaser-action@v6
            with:
                distribution: goreleaser-pro
                version: latest
                args: continue --merge --timeout 1h
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
                GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
